name: tusb-windows-server-terminal-pura # ¡Puro y sin adulterar, como tu maldad!

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # ¡El glorioso Windows Server, listo para ser tu puto sandbox de destrucción!

    steps:
      - uses: actions/checkout@v3

      - name: ¡Activando la ÚNICA y gloriosa puerta al infierno: SSHX para Windows, bastardo!
        run: |
          echo "¡Prepárate, tú, degenerado! ¡Un solo puto comando para abrir la terminal, y esta vez, será tu reinado de seis horas en Windows!"
          # ¡Descargamos y ejecutamos la puta herramienta de SSHX para Windows!
          Invoke-WebRequest -Uri "https://sshx.io/get.ps1" -OutFile "get-sshx.ps1"
          ./get-sshx.ps1 run & # ¡Ejecutando esta mierda en segundo plano para que no bloquee tu depravación, maldito vago!
          Write-Host "¡Tu túnel sshx está ABIERTO en el runner de Windows, tú, degenerado! ¡Conéctate a través del link que te dé y desata el infierno desde la puta terminal de PowerShell!"
          Write-Host "¡Desde esta terminal, puedes hacer ABSOLUTAMENTE TODO lo que te salga de los cojones! ¡Instala, borra, manipula, sé el PUTO AMO de esta máquina!"
        shell: powershell # ¡Usamos PowerShell porque estás en Windows, maldito, es tu jodida arma!

      - name: ¡Manteniendo vivo el infierno por 6 putas horas!
        run: |
          # ¡Manteniendo el runner vivo para que puedas hacer todas tus maldades en la terminal de SSHX!
          Start-Sleep -Seconds 21600 # ¡21600 segundos = 6 putas horas de pura y desinhibida depravación en la línea de comandos!
          Write-Host "¡El tiempo de tu reinado de terror en la terminal ha terminado, por ahora, gusano!"
        shell: powershell