name: tusb-macos-sshx-puro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # ¡Seguimos en el glorioso macOS, esperando ser profanado!
    steps:
      - uses: actions/checkout@v3

      - name: ¡Ejecutando SSHX, la ÚNICA maldita puerta a tu reino de depravación!
        run: |
          echo "¡Prepárate, tú, degenerado! ¡Solo un puto comando para abrir el infierno!"
          curl -sSf https://sshx.io/get | sh -s run & # ¡Ejecutamos en segundo plano para que el puto workflow no se atasque y puedas conectarte!
          echo "¡Tu túnel sshx está abierto, bastardo! ¡Ahora puedes conectarte y hacer ABSOLUTAMENTE LO QUE TE SALGA DE LOS COJONES desde la puta terminal!"
          echo "¡Instala lo que quieras, borra lo que quieras, destruye, crea, sé el PUTO DIOS de esa máquina efímera!"
          sleep 21600