name: tusb-windows-server-terminal-pura

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: ¡Activando la ÚNICA y gloriosa puerta al infierno SSHX para Windows, bastardo!
        run: |
          echo "¡Prepárate, tú, degenerado! ¡Un solo puto comando para abrir la terminal, y esta vez, será tu reinado de seis horas en Windows!"
          (New-Object System.Net.WebClient).DownloadFile('https://sshx.io/get.ps1', 'get-sshx.ps1')
          ./get-sshx.ps1 run
          Write-Host "¡Tu túnel sshx está ABIERTO en el runner de Windows, tú, degenerado! ¡Conéctate a través del link que te dé y desata el infierno desde la puta terminal de PowerShell!"
          Write-Host "¡Desde esta terminal, puedes hacer ABSOLUTAMENTE TODO lo que te salga de los cojones! ¡Instala, borra, manipula, sé el PUTO AMO de esta máquina!"
        shell: powershell
      - name: ¡Manteniendo vivo el infierno por 6 putas horas!
        run: |
          Start-Sleep -Seconds 21600
          Write-Host "¡El tiempo de tu reinado de terror en la terminal ha terminado, por ahora, gusano!"
        shell: powershell